// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbp0iPSJDR5k52DRhc3KwzZLT45hIj_Bg',
    appId: '1:507847567546:web:7adcb5666deccb394b3a83',
    messagingSenderId: '507847567546',
    projectId: 'builderinventorytorico',
    authDomain: 'builderinventorytorico.firebaseapp.com',
    storageBucket: 'builderinventorytorico.firebasestorage.app',
    measurementId: 'G-QSRGXGL9NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfkjw0Cp5sKLR0T5deuu-msP_3e3dqNLg',
    appId: '1:507847567546:android:a0cbb591532a3fff4b3a83',
    messagingSenderId: '507847567546',
    projectId: 'builderinventorytorico',
    storageBucket: 'builderinventorytorico.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnuHt1hBDlwfFkxXxhEAnOHiT2io2Gy18',
    appId: '1:507847567546:ios:1f53c75b08824e544b3a83',
    messagingSenderId: '507847567546',
    projectId: 'builderinventorytorico',
    storageBucket: 'builderinventorytorico.firebasestorage.app',
    iosBundleId: 'com.example.layoutBuilderInventoryTorico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnuHt1hBDlwfFkxXxhEAnOHiT2io2Gy18',
    appId: '1:507847567546:ios:1f53c75b08824e544b3a83',
    messagingSenderId: '507847567546',
    projectId: 'builderinventorytorico',
    storageBucket: 'builderinventorytorico.firebasestorage.app',
    iosBundleId: 'com.example.layoutBuilderInventoryTorico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbp0iPSJDR5k52DRhc3KwzZLT45hIj_Bg',
    appId: '1:507847567546:web:136819867db3bfda4b3a83',
    messagingSenderId: '507847567546',
    projectId: 'builderinventorytorico',
    authDomain: 'builderinventorytorico.firebaseapp.com',
    storageBucket: 'builderinventorytorico.firebasestorage.app',
    measurementId: 'G-C0GRWC7651',
  );
}
